- name: configure backend server
  hosts: backend
  become: yes
  tasks: 
  - name: disable current nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodesj 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name : install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: craetwc expenser user
    ansible.builtin.user:
      name: expense